import HautevilleHouse.ConvergenceDivergenceSeriesSequencesFunctionsTheoremCanonicalLaneLean.ConvergenceDivergenceDefinitions
import HautevilleHouse.ConvergenceDivergenceSeriesSequencesFunctionsTheoremCanonicalLaneLean.SeriesDivergencePackage
import HautevilleHouse.ConvergenceDivergenceSeriesSequencesFunctionsTheoremCanonicalLaneLean.UniformConvergenceFunctionalPackage
import HautevilleHouse.ConvergenceDivergenceSeriesSequencesFunctionsTheoremCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.ConvergenceDivergenceSeriesSequencesFunctionsTheoremCanonicalLaneLean.GateLemmas
import HautevilleHouse.ConvergenceDivergenceSeriesSequencesFunctionsTheoremCanonicalLaneLean.FinalTheorem

namespace HautevilleHouse
namespace ConvergenceDivergenceSeriesSequencesFunctionsTheoremCanonicalLaneLean

-- Root module for the Convergence Divergence Series Sequences Functions Theorem package.
-- This module imports all the submodules to ensure they are in the dependency graph.

def convergenceDivergenceRootModule : Bool := true

end ConvergenceDivergenceSeriesSequencesFunctionsTheoremCanonicalLaneLean
end HautevilleHouse